const esbuild = require('esbuild');

// assets/css/icons.css is generated by scripts/subset-icons.js rather than hand-edited, but it's
// watched too so that running `npm run icons` in another terminal still refreshes icons.min.css.
const targets = [
  ['assets/js/main.js', 'assets/js/main.min.js'],
  ['assets/css/styles.css', 'assets/css/styles.min.css'],
  ['assets/css/icons.css', 'assets/css/icons.min.css'],
];

async function main() {
  const contexts = await Promise.all(
    targets.map(([entry, outfile]) => esbuild.context({ entryPoints: [entry], outfile, minify: true }))
  );

  await Promise.all(contexts.map((c) => c.watch()));
  console.log(`Watching ${targets.map(([entry]) => entry).join(', ')} for changes...`);
}

main();
